### ISSUE TITLE
Fix environment variables for platform account properties 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-samples#108]
As a user, I'm attempting to retry [limiting_concurrent_task_executions](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_limiting_concurrent_task_executions) sample locally in my environment; however, I'm unable to override the default limit of 20.

Issues:

- [ ] The env-var `SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_LOCAL_ACCOUNTS[DEFAULT].MAXIMUM_CONCURRENT_TASKS 3` includes `.`, which is wrong. It should be `_` instead.

- [ ] The env-var `SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_LOCAL_ACCOUNTS[DEFAULT].MAXIMUM_CONCURRENT_TASKS 3` is missing `_DEPLOYMENT` prefix.

- [ ] The correct env-var should be `SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_LOCAL_ACCOUNTS[DEFAULT]_DEPLOYMENT_MAXIMUMCONCURRENTTASKS 3`.

- [ ] Once when we update the sample/docs, we would have to then amend the Microsite demo with the correct property, too. _(See [limiting-concurrent-task-executions](https://dataflow.spring.io/docs/recipes/file-ingest/sftp-to-jdbc/#limiting-concurrent-task-executions))_

- [ ] Update SCDF ref. guide to point to the correct property. _(See [docs](https://docs.spring.io/spring-cloud-dataflow/docs/2.2.0.M1/reference/htmlsingle/#spring-cloud-dataflow-task-limit-concurrent-executions))_

**Comment by dturanski** [comment]
Does uppercase 'DEFAULT' work for you? I Thought the account name is case sensitive.

**Comment by dturanski** [comment]
@sabbyanandan - This is also wrong:  https://dataflow.spring.io/docs/installation/cloudfoundry/cf-cli/

**Comment by dturanski** [comment]
and here https://docs.spring.io/spring-cloud-skipper/docs/current/reference/htmlsingle/#skipper-installation-cloudfoundry
