### ISSUE TITLE
File ingest reference architecture

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-samples#66]
- [x] spring-cloud-stream-app-starters/sftp#12
- [x] spring-cloud-stream-app-starters/app-starters-release#141
- [x] spring-cloud-stream-app-starters/app-starters-release#130
- [x] spring-cloud-stream-app-starters/app-starters-release#151
- [x] spring-cloud-stream-app-starters/core#45
- [x] spring-cloud/spring-cloud-dataflow-samples#75 
- [x] spring-cloud/spring-cloud-dataflow-samples#74

**Comment by sabbyanandan** [comment]
@dturanski: Thanks for chasing all the loose ends to design and develop the e2e solution architecture. We now have a repeatable sample for both CF and K8s. I'm marking the epic as done.
